### ISSUE TITLE
Add personal pool funding

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-contracts#15]
A user should be able to create and maintain a list of receivers. The receivers should be automatically getting ETH.

https://www.notion.so/monadic/Funding-Pools-protocol-35d73282538c4d21aa096753fea540e3

**Comment by cloudhead** [comment]
Not sure what you mean by "automatically", do you mean on-demand?

**Comment by CodeSandwich** [comment]
Sorry for the description being vague, I've jotted it down as a placeholder, the real thing is behind the link to Notion. It's automatically granting right to receiver more and more, but the actual paying out is on-demand.
