### ISSUE TITLE
Make pools ERC-20 compatible

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-contracts#19]
We need to be able to deploy a pool contract, which will be pushing donations in arbitrary ERC-20 tokens. The token contract can be passed during construction, it's fine to have deployed one per token.

**Comment by geigerzaehler** [comment]
> We need to be able to deploy a pool contract, which will be pushing donations in arbitrary ERC-20 tokens.

This sounds like one pool contract can handle arbitrary ERC-20s. If I understand this correctly though we want the pool contract to be generic over the used ERC-20 token, right?

**Comment by CodeSandwich** [comment]
Right, we want a contract to be generic over all ERC-20 tokens, but we want to attach it to exactly one token (ERC-20 contract address) on deployment.
