### ISSUE TITLE
Add batch sender update

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-contracts#50]
The sender has to make at least 3 steps to start donating: set a per month rate, top up the account and configure a list of receivers, which itself can take up to tens of transactions. This is a slow and expensive process.

We need a batch update transaction, which can take all these parameters and set them all at once.

**Comment by NunoAlexandre** [comment]
We have the following uses cases for the outgoing support flow:

1. Onboarding
The user's pool is voided and, ideally, we would let the user do the following in one single transaction:
    - Set their pool's balance (i.e, top-up) + set the monthly rate + set a list of receivers

2. After onboarding
The user has set their preferred starting state and can now make changes to said state. Here, we want to offer three possible transactions to the user:
    - Update the monthly rate + the list of receivers. This transaction would be seen as "saving the pool"
    - Let the user top-up
    - Let the user drain their pool balance

As for the incoming support flow, we only the one transaction we already have to `collectFunds`.
